name: Deploy to Gigalixir

on:
  push:
    branches: [ main ] # Change to 'master' if your main branch is called master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: gigalixir/gigalixir-action@v1
        with:
          GIGALIXIR_USERNAME: ${{ secrets.GIGALIXIR_EMAIL }}
          GIGALIXIR_PASSWORD: ${{ secrets.GIGALIXIR_API_KEY }}
          GIGALIXIR_APP: madrastna-backend
