name: Deploy to Gigalixir

on:
  push:
<<<<<<< HEAD
    branches: [ main ] 
=======
    branches: [ main ]
>>>>>>> 3b5af4f (chore: sync backend recent changes from gigalixir branch)

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
<<<<<<< HEAD
      
=======

>>>>>>> 3b5af4f (chore: sync backend recent changes from gigalixir branch)
      # Using @main instead of @v1 to bypass the version error
      - uses: gigalixir/gigalixir-action@main
        with:
          gigalixir_email: ${{ secrets.GIGALIXIR_EMAIL }}
          gigalixir_api_key: ${{ secrets.GIGALIXIR_API_KEY }}
          app_name: madrastna-backend
